config/routes.rb
Playoutside::Application.routes.draw do
  root 'parks#index'

  devise_for :users
  
  resources :users
  resources :parks
end

app/models/park.rb
class Park<ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parks_controller.rb
class ParksController<ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %>| Play Outside</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><b>playoutside</b></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>
            </ul>

            <ul class="nav navbar-nav navbar-right">

              <% if !user_signed_in? %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>

              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        <% end %>
      </div>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/parks/index.html.erb
<% content_for(:title, "Home | Play Outside") %>

<h1> Welcome! </h1>

<%= link_to "Parks", parks_path%>